const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
function json(d,s){return new Response(JSON.stringify(d),{status:s||200,headers:{...CORS,"Content-Type":"application/json"}})}
const LM=365*100*86400000;
export default{async fetch(r,e){if(r.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(r.url),p=u.pathname;try{
if(p==="/api/verify"&&r.method==="POST"){const{key,email}=await r.json();if(!key||typeof key!="string"||key.length<8)return json({valid:false,error:"Invalid key"});
const kv=await e.SVG_PRO_KEYS.get(key);if(kv){const d=JSON.parse(kv);if(!d.expiresAt||d.expiresAt>Date.now())return json({valid:true,key,license:{id:key},meta:{email:d.email||"",activatedAt:d.activatedAt||Date.now(),expiresAt:d.expiresAt||Date.now()+LM,source:d.source||"kv"}});await e.SVG_PRO_KEYS.delete(key);return json({valid:false,error:"Expired"})}
let result;try{result=await(await fetch("https://api.lemonsqueezy.com/v1/licenses/activate",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({license_key:key,instance_name:"svgcompressor.pages.dev"})})).json()}catch(er){return json({valid:false,error:"Unavailable"},503)}
if(result.activated===true){const n=Date.now();await e.SVG_PRO_KEYS.put(key,JSON.stringify({key,email:email||result.meta?.customer_email||"",activatedAt:n,expiresAt:n+LM}));return json({valid:true,key,meta:{email:email||result.meta?.customer_email||"",activatedAt:n,expiresAt:n+LM,source:"ls"}})}
return json({valid:false,error:result.error||"Not found"},400)}
if(p==="/api/status"&&r.method==="POST"){const{key}=await r.json();if(!key)return json({pro:false});const s=await e.SVG_PRO_KEYS.get(key);if(!s)return json({pro:false});const d=JSON.parse(s),ex=d.expiresAt&&d.expiresAt<Date.now();if(ex){await e.SVG_PRO_KEYS.delete(key);return json({pro:false,expired:true})}return json({pro:true,key,email:d.email||"",activatedAt:d.activatedAt,expiresAt:d.expiresAt,daysLeft:d.expiresAt?Math.floor((d.expiresAt-Date.now())/86400000):36500,source:d.source||"ls"})}
if(p==="/api/account"&&r.method==="GET"){const k=u.searchParams.get("key");if(!k)return json({error:"No key"},400);const s=await e.SVG_PRO_KEYS.get(k);if(!s)return json({error:"Not found"},404);const d=JSON.parse(s),ex=d.expiresAt&&d.expiresAt<Date.now();return json({status:ex?"expired":"active",email:d.email||"N/A",activatedAt:new Date(d.activatedAt).toISOString().split("T")[0],expiresAt:new Date(d.expiresAt).toISOString().split("T")[0],daysLeft:ex?0:Math.floor((d.expiresAt-Date.now())/86400000),key:d.key})}
if(p==="/api/lookup-checkout"&&r.method==="GET"){const c=u.searchParams.get("checkout_id");if(!c)return json({found:false});const vb=await e.SVG_PRO_KEYS.get("checkout:"+c);if(!vb)return json({found:false});const vd=JSON.parse(vb);return json({found:true,key:vd.key,email:vd.email})}
if(p==="/api/lookup-email"&&r.method==="GET"){const em=u.searchParams.get("email");if(!em)return json({found:false});const es=await e.SVG_PRO_KEYS.get("email:"+em);if(!es)return json({found:false});const ed=JSON.parse(es);return json({found:true,key:ed.key,email:em})}
if(p==="/api/webhook"&&r.method==="POST"){try{const pb=await r.json(),en=pb.meta?.event_name||"";if(en==="order_created"){const od=pb.data?.attributes||{},em=od.user_email||"",oi=od.order_number||"",cd=pb.meta?.custom_data||{},ci=cd.checkout_id||"",lk=od.license_key?.key||Array.from(crypto.getRandomValues(new Uint8Array(8)),function(b){return b.toString(36).toUpperCase()}).join(""),n=Date.now();await e.SVG_PRO_KEYS.put(lk,JSON.stringify({key:lk,email:em,activatedAt:n,expiresAt:n+LM,lsOrderId:oi,status:od.status||""}));if(ci)await e.SVG_PRO_KEYS.put("checkout:"+ci,JSON.stringify({key:lk,email:em}));if(em)await e.SVG_PRO_KEYS.put("email:"+em,JSON.stringify({key:lk}));return json({received:true,action:"created",key:lk})}return json({received:true,event:en})}catch(er){return json({received:false,error:er.message},400)}}
if(p==="/api/webhook-test"&&r.method==="GET"){const ci=u.searchParams.get("checkout_id")||"test_"+(Math.random().toString(36).slice(2,8));const lk="TESTKEY-"+Array.from(crypto.getRandomValues(new Uint8Array(6)),function(b){return b.toString(36).toUpperCase()}).join("");const em=u.searchParams.get("email")||"test@example.com";const nn=Date.now();await e.SVG_PRO_KEYS.put(lk,JSON.stringify({key:lk,email:em,activatedAt:nn,expiresAt:nn+LM,lsOrderId:"TEST",status:"paid",source:"test"}));await e.SVG_PRO_KEYS.put("checkout:"+ci,JSON.stringify({key:lk,email:em}));await e.SVG_PRO_KEYS.put("email:"+em,JSON.stringify({key:lk}));return json({success:true,key:lk,checkout_id:ci,email:em})}
if(p==="/api/event"&&r.method==="POST"){const b=await r.text();return json({ok:true})}
return json({status:"ok",service:"svg-verify",version:"2.1.0",endpoints:["/api/verify","/api/status","/api/account","/api/lookup-checkout","/api/lookup-email","/api/webhook","/api/webhook-test","/api/event"]})}
catch(e){return json({error:"Internal error"},500)}}}
